Default: &defaults
  user: *******
  password: *******
  host: paperserver.jp
  database: PaperServer
  connections: 10

Development:
  <<: *defaults

Testing:
  database: Yesod_test
  <<: *defaults

Staging:
  database: Yesod_staging
  connections: 100
  <<: *defaults

Production:
  database: PaperServer
  connections: 100
#  host: localhost
  <<: *defaults
